# inherit_from: ../.rubocop.yml

# Common configuration.
AllCops:
  # Include gemspec and Rakefile
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/*.gemspec'
    - '**/*.jbuilder'
    - '**/*.rb'
  Exclude:
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'
    - 'bin/spring'
    - 'bin/update'
    - 'config.ru'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'secure_rails'
    - 'test/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

# # Not compatible with Rails < 4
# ActionFilter:
#   Enabled: false

AlignParameters:
  EnforcedStyle: with_fixed_indentation

ClassLength:
  Max: 300

Encoding:
  Enabled: false

IndentHash:
  EnforcedStyle: consistent

HasAndBelongsToMany:
  Enabled: false

Layout/AlignHash:
  # Alignment of entries using colon as separator. Valid values are:
  #
  # key - left alignment of keys
  # a: 0
  # bb: 1
  # separator - alignment of colons, keys are right aligned
  # a: 0
  # bb: 1
  # table - left alignment of keys and values
  # a: 0
  # bb: 1
  EnforcedColonStyle: table

Layout/SpaceBeforeFirstArg:
  Enabled: false

LineLength:
  Max: 120

# Default 10
MethodLength:
  Max: 30

# Default 15
Metrics/AbcSize:
  Max: 30

StringLiterals:
  EnforcedStyle: double_quotes

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: percent_x
