sudo: required

language: ruby

# ignore lint error. addons.apt.packages is valid
addons:
  apt:
    packages:
      - libgmp-dev
      - libxml2
      - libxml2-dev

# rvm: 2.3.1 is buggy
before_install:
  - rvm get stable --auto-dotfiles
  - rvm install 2.3.1 --binary
  - gem install bundler
  - bundle config build.nokogiri --use-system-libraries

install: bundle install --jobs=3 --retry=3 --without development production

cache:
  - apt
  - bundler

script: bundle exec rspec