---
sudo: false
language: ruby
rvm:
  - 2.6.5

cache:
  - bundler

before_install:
  - gem install bundler -v 1.16.2
  - gem install bundler-audit -v 0.6.1

# We don't want deployment mode
# It gets confusing when the gem we're building is part of the Gemfile.lock
install:
  - bundle install --jobs=3 --retry=3 --path vendor/bundle

script:
  - bundle audit --update
  - bundle exec rubocop -D Gemfile safety_goggles.gemspec lib/
  - bundle exec rake spec

before_deploy:
  - mkdir -p ~/.gem
  - 'echo ":rubygems_api_key: ${RUBYGEMS_API_KEY:?}" > ~/.gem/credentials'
  - chmod 600 ~/.gem/credentials
  - gem build *.gemspec

deploy:
  provider: script
  script: gem push *.gemspec
  on:
    tags: true
